// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrTgX1_dLFcuijKpKju4UbZYV3fOBW3TQ',
    appId: '1:135540186701:web:66d90975c186dae2d7c604',
    messagingSenderId: '135540186701',
    projectId: 'as-jala',
    authDomain: 'as-jala.firebaseapp.com',
    storageBucket: 'as-jala.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXFKFu-4HN2zgor0hAdVl-i2R-RNJUGyo',
    appId: '1:135540186701:android:8500d7257d40296cd7c604',
    messagingSenderId: '135540186701',
    projectId: 'as-jala',
    storageBucket: 'as-jala.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4hOvcRJUn9LPVXdjsYvX5HH-098_BmKc',
    appId: '1:135540186701:ios:5d4a1b00c399c44ed7c604',
    messagingSenderId: '135540186701',
    projectId: 'as-jala',
    storageBucket: 'as-jala.firebasestorage.app',
    iosBundleId: 'com.example.jalaAs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4hOvcRJUn9LPVXdjsYvX5HH-098_BmKc',
    appId: '1:135540186701:ios:5d4a1b00c399c44ed7c604',
    messagingSenderId: '135540186701',
    projectId: 'as-jala',
    storageBucket: 'as-jala.firebasestorage.app',
    iosBundleId: 'com.example.jalaAs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxuAIxOnFLilK96dnyH3W3IAl7TpM6xEM',
    appId: '1:135540186701:web:03ce832bd5d626dcd7c604',
    messagingSenderId: '135540186701',
    projectId: 'as-jala',
    authDomain: 'as-jala.firebaseapp.com',
    storageBucket: 'as-jala.firebasestorage.app',
  );
}
